# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c042280d9551dbd07a5fd613204338bcbf7b57d71b6b7555ae7591ade9ba94aba3c8ccc532f7ded5ea93b16f761e978173ef7cee7220b946695bb2cf50d7266

test:
  secret_key_base: 2b25abe0e0feba9fbd50ae487b0025bb772713c5c03ae88371888875fbbb26b60783aefac6755d3023b89a1e4606b86f28bd93caec2276c5d89326f03dbee279

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
